// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: hello.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamConversationsClient is the client API for StreamConversations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamConversationsClient interface {
	Converstaion(ctx context.Context, opts ...grpc.CallOption) (StreamConversations_ConverstaionClient, error)
}

type streamConversationsClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamConversationsClient(cc grpc.ClientConnInterface) StreamConversationsClient {
	return &streamConversationsClient{cc}
}

func (c *streamConversationsClient) Converstaion(ctx context.Context, opts ...grpc.CallOption) (StreamConversations_ConverstaionClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamConversations_ServiceDesc.Streams[0], "/StreamConversations/Converstaion", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamConversationsConverstaionClient{stream}
	return x, nil
}

type StreamConversations_ConverstaionClient interface {
	Send(*StreamRequest) error
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type streamConversationsConverstaionClient struct {
	grpc.ClientStream
}

func (x *streamConversationsConverstaionClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamConversationsConverstaionClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamConversationsServer is the server API for StreamConversations service.
// All implementations must embed UnimplementedStreamConversationsServer
// for forward compatibility
type StreamConversationsServer interface {
	Converstaion(StreamConversations_ConverstaionServer) error
	mustEmbedUnimplementedStreamConversationsServer()
}

// UnimplementedStreamConversationsServer must be embedded to have forward compatible implementations.
type UnimplementedStreamConversationsServer struct {
}

func (UnimplementedStreamConversationsServer) Converstaion(StreamConversations_ConverstaionServer) error {
	return status.Errorf(codes.Unimplemented, "method Converstaion not implemented")
}
func (UnimplementedStreamConversationsServer) mustEmbedUnimplementedStreamConversationsServer() {}

// UnsafeStreamConversationsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamConversationsServer will
// result in compilation errors.
type UnsafeStreamConversationsServer interface {
	mustEmbedUnimplementedStreamConversationsServer()
}

func RegisterStreamConversationsServer(s grpc.ServiceRegistrar, srv StreamConversationsServer) {
	s.RegisterService(&StreamConversations_ServiceDesc, srv)
}

func _StreamConversations_Converstaion_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamConversationsServer).Converstaion(&streamConversationsConverstaionServer{stream})
}

type StreamConversations_ConverstaionServer interface {
	Send(*StreamResponse) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type streamConversationsConverstaionServer struct {
	grpc.ServerStream
}

func (x *streamConversationsConverstaionServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamConversationsConverstaionServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamConversations_ServiceDesc is the grpc.ServiceDesc for StreamConversations service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamConversations_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StreamConversations",
	HandlerType: (*StreamConversationsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Converstaion",
			Handler:       _StreamConversations_Converstaion_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hello.proto",
}
